# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoSUST.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(694, 671)
        Dialog.setMaximumSize(QtCore.QSize(694, 700))
        font = QtGui.QFont()
        font.setPointSize(6)
        Dialog.setFont(font)
        Dialog.setAcceptDrops(True)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(9, 9, 9, 9)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.toolBox.setFont(font)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setStyleSheet("\n"
"font: 75 italic 10pt \"MS Shell Dlg 2\";")
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 676, 473))
        self.page.setObjectName("page")
        self.SetBtnHelp = QtWidgets.QPushButton(self.page)
        self.SetBtnHelp.setGeometry(QtCore.QRect(581, 240, 72, 24))
        self.SetBtnHelp.setMaximumSize(QtCore.QSize(72, 24))
        self.SetBtnHelp.setObjectName("SetBtnHelp")
        self.SetBtnAbout = QtWidgets.QPushButton(self.page)
        self.SetBtnAbout.setGeometry(QtCore.QRect(581, 270, 72, 24))
        self.SetBtnAbout.setMaximumSize(QtCore.QSize(72, 24))
        self.SetBtnAbout.setObjectName("SetBtnAbout")
        self.SetBtnBox = QtWidgets.QDialogButtonBox(self.page)
        self.SetBtnBox.setGeometry(QtCore.QRect(581, 180, 71, 56))
        self.SetBtnBox.setMaximumSize(QtCore.QSize(71, 114))
        self.SetBtnBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SetBtnBox.setOrientation(QtCore.Qt.Vertical)
        self.SetBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.SetBtnBox.setCenterButtons(True)
        self.SetBtnBox.setObjectName("SetBtnBox")
        self.BaseLayerLbl = QtWidgets.QLabel(self.page)
        self.BaseLayerLbl.setGeometry(QtCore.QRect(180, 10, 461, 20))
        self.BaseLayerLbl.setObjectName("BaseLayerLbl")
        self.OutlEdt = QtWidgets.QLineEdit(self.page)
        self.OutlEdt.setGeometry(QtCore.QRect(180, 40, 461, 20))
        self.OutlEdt.setObjectName("OutlEdt")
        self.RetriveFileTBtn = QtWidgets.QToolButton(self.page)
        self.RetriveFileTBtn.setGeometry(QtCore.QRect(140, 40, 25, 21))
        self.RetriveFileTBtn.setObjectName("RetriveFileTBtn")
        self.listAllFields = QtWidgets.QListWidget(self.page)
        self.listAllFields.setGeometry(QtCore.QRect(10, 90, 211, 381))
        self.listAllFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listAllFields.setObjectName("listAllFields")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(230, 80, 331, 128))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.addLayerBtnENV = QtWidgets.QPushButton(self.groupBox)
        self.addLayerBtnENV.setGeometry(QtCore.QRect(20, 40, 51, 23))
        self.addLayerBtnENV.setObjectName("addLayerBtnENV")
        self.listEnvFields = QtWidgets.QListWidget(self.groupBox)
        self.listEnvFields.setGeometry(QtCore.QRect(90, 20, 231, 100))
        self.listEnvFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listEnvFields.setObjectName("listEnvFields")
        self.removeLayerBtnENV = QtWidgets.QPushButton(self.groupBox)
        self.removeLayerBtnENV.setGeometry(QtCore.QRect(20, 70, 51, 23))
        self.removeLayerBtnENV.setObjectName("removeLayerBtnENV")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 210, 331, 128))
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.removeLayerBtnECO = QtWidgets.QPushButton(self.groupBox_2)
        self.removeLayerBtnECO.setGeometry(QtCore.QRect(20, 60, 51, 23))
        self.removeLayerBtnECO.setObjectName("removeLayerBtnECO")
        self.listEcoFields = QtWidgets.QListWidget(self.groupBox_2)
        self.listEcoFields.setGeometry(QtCore.QRect(90, 20, 231, 100))
        self.listEcoFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listEcoFields.setObjectName("listEcoFields")
        self.addLayerBtnECO = QtWidgets.QPushButton(self.groupBox_2)
        self.addLayerBtnECO.setGeometry(QtCore.QRect(20, 30, 51, 23))
        self.addLayerBtnECO.setObjectName("addLayerBtnECO")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 340, 331, 130))
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.addLayerBtnSOC = QtWidgets.QPushButton(self.groupBox_4)
        self.addLayerBtnSOC.setGeometry(QtCore.QRect(20, 30, 51, 23))
        self.addLayerBtnSOC.setObjectName("addLayerBtnSOC")
        self.removeLayerBtnSOC = QtWidgets.QPushButton(self.groupBox_4)
        self.removeLayerBtnSOC.setGeometry(QtCore.QRect(20, 60, 51, 23))
        self.removeLayerBtnSOC.setObjectName("removeLayerBtnSOC")
        self.listSocFields = QtWidgets.QListWidget(self.groupBox_4)
        self.listSocFields.setGeometry(QtCore.QRect(90, 20, 231, 100))
        self.listSocFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listSocFields.setObjectName("listSocFields")
        self.EcoFieldsLbl_2 = QtWidgets.QLabel(self.page)
        self.EcoFieldsLbl_2.setGeometry(QtCore.QRect(30, 10, 81, 21))
        self.EcoFieldsLbl_2.setObjectName("EcoFieldsLbl_2")
        self.EcoFieldsLbl_3 = QtWidgets.QLabel(self.page)
        self.EcoFieldsLbl_3.setGeometry(QtCore.QRect(30, 40, 81, 21))
        self.EcoFieldsLbl_3.setObjectName("EcoFieldsLbl_3")
        self.LblLogo = QtWidgets.QLabel(self.page)
        self.LblLogo.setGeometry(QtCore.QRect(580, 90, 81, 71))
        self.LblLogo.setText("")
        self.LblLogo.setScaledContents(True)
        self.LblLogo.setObjectName("LblLogo")
        self.LoadProgressBar = QtWidgets.QProgressBar(self.page)
        self.LoadProgressBar.setGeometry(QtCore.QRect(610, 340, 21, 131))
        self.LoadProgressBar.setProperty("value", 0)
        self.LoadProgressBar.setOrientation(QtCore.Qt.Vertical)
        self.LoadProgressBar.setObjectName("LoadProgressBar")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_4.raise_()
        self.SetBtnHelp.raise_()
        self.SetBtnAbout.raise_()
        self.SetBtnBox.raise_()
        self.BaseLayerLbl.raise_()
        self.OutlEdt.raise_()
        self.RetriveFileTBtn.raise_()
        self.listAllFields.raise_()
        self.EcoFieldsLbl_2.raise_()
        self.EcoFieldsLbl_3.raise_()
        self.LblLogo.raise_()
        self.LoadProgressBar.raise_()
        self.toolBox.addItem(self.page, "")
        self.EnvironmentaleQTbox = QtWidgets.QWidget()
        self.EnvironmentaleQTbox.setGeometry(QtCore.QRect(0, 0, 676, 473))
        self.EnvironmentaleQTbox.setObjectName("EnvironmentaleQTbox")
        self.EnvLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvLbl.setGeometry(QtCore.QRect(9, 9, 51, 16))
        self.EnvLbl.setObjectName("EnvLbl")
        self.EnvMapNameLbl = QtWidgets.QLabel(self.EnvironmentaleQTbox)
        self.EnvMapNameLbl.setGeometry(QtCore.QRect(69, 8, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.EnvMapNameLbl.setFont(font)
        self.EnvMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.EnvMapNameLbl.setObjectName("EnvMapNameLbl")
        self.EnvTEdit = QtWidgets.QTextEdit(self.EnvironmentaleQTbox)
        self.EnvTEdit.setGeometry(QtCore.QRect(10, 420, 531, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.EnvTEdit.sizePolicy().hasHeightForWidth())
        self.EnvTEdit.setSizePolicy(sizePolicy)
        self.EnvTEdit.setObjectName("EnvTEdit")
        self.EnvHelpBtn = QtWidgets.QPushButton(self.EnvironmentaleQTbox)
        self.EnvHelpBtn.setGeometry(QtCore.QRect(560, 420, 102, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvHelpBtn.sizePolicy().hasHeightForWidth())
        self.EnvHelpBtn.setSizePolicy(sizePolicy)
        self.EnvHelpBtn.setMaximumSize(QtCore.QSize(110, 16777215))
        self.EnvHelpBtn.setObjectName("EnvHelpBtn")
        self.line_2 = QtWidgets.QFrame(self.EnvironmentaleQTbox)
        self.line_2.setGeometry(QtCore.QRect(9, 36, 657, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.EnvironmentaleQTbox)
        self.line_4.setGeometry(QtCore.QRect(10, 400, 660, 15))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.EnvironmentaleQTbox)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 60, 661, 331))
        self.groupBox_11.setObjectName("groupBox_11")
        self.EnvGetWeightBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.EnvGetWeightBtn.setGeometry(QtCore.QRect(550, 290, 104, 24))
        self.EnvGetWeightBtn.setMaximumSize(QtCore.QSize(104, 16777215))
        self.EnvGetWeightBtn.setObjectName("EnvGetWeightBtn")
        self.EnvWeighTableWidget = QtWidgets.QTableWidget(self.groupBox_11)
        self.EnvWeighTableWidget.setGeometry(QtCore.QRect(20, 31, 630, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.EnvWeighTableWidget.setSizePolicy(sizePolicy)
        self.EnvWeighTableWidget.setAcceptDrops(False)
        self.EnvWeighTableWidget.setDragEnabled(True)
        self.EnvWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.EnvWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.EnvWeighTableWidget.setRowCount(0)
        self.EnvWeighTableWidget.setObjectName("EnvWeighTableWidget")
        self.EnvWeighTableWidget.setColumnCount(0)
        self.EnvWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.EnvWeighTableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.EnvWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.EnvWeighTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.EnvWeighTableWidget.verticalHeader().setStretchLastSection(True)
        self.EnvProgressBar = QtWidgets.QProgressBar(self.groupBox_11)
        self.EnvProgressBar.setGeometry(QtCore.QRect(170, 290, 371, 25))
        self.EnvProgressBar.setProperty("value", 0)
        self.EnvProgressBar.setObjectName("EnvProgressBar")
        self.EnvSaveCfgBtn = QtWidgets.QPushButton(self.groupBox_11)
        self.EnvSaveCfgBtn.setGeometry(QtCore.QRect(20, 290, 104, 24))
        self.EnvSaveCfgBtn.setObjectName("EnvSaveCfgBtn")
        self.toolBox.addItem(self.EnvironmentaleQTbox, "")
        self.EconomicsQTBox = QtWidgets.QWidget()
        self.EconomicsQTBox.setGeometry(QtCore.QRect(0, 0, 676, 473))
        self.EconomicsQTBox.setObjectName("EconomicsQTBox")
        self.EcoLbl = QtWidgets.QLabel(self.EconomicsQTBox)
        self.EcoLbl.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.EcoLbl.setObjectName("EcoLbl")
        self.EcoTEdit = QtWidgets.QTextEdit(self.EconomicsQTBox)
        self.EcoTEdit.setGeometry(QtCore.QRect(10, 420, 530, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.EcoTEdit.sizePolicy().hasHeightForWidth())
        self.EcoTEdit.setSizePolicy(sizePolicy)
        self.EcoTEdit.setObjectName("EcoTEdit")
        self.EcoHelpBtn = QtWidgets.QPushButton(self.EconomicsQTBox)
        self.EcoHelpBtn.setGeometry(QtCore.QRect(560, 420, 99, 24))
        self.EcoHelpBtn.setObjectName("EcoHelpBtn")
        self.EcoMapNameLbl = QtWidgets.QLabel(self.EconomicsQTBox)
        self.EcoMapNameLbl.setGeometry(QtCore.QRect(90, 9, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.EcoMapNameLbl.setFont(font)
        self.EcoMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.EcoMapNameLbl.setObjectName("EcoMapNameLbl")
        self.line_5 = QtWidgets.QFrame(self.EconomicsQTBox)
        self.line_5.setGeometry(QtCore.QRect(8, 25, 657, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.EconomicsQTBox)
        self.line_7.setGeometry(QtCore.QRect(10, 400, 660, 15))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.groupBox_10 = QtWidgets.QGroupBox(self.EconomicsQTBox)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 40, 661, 341))
        self.groupBox_10.setObjectName("groupBox_10")
        self.EcoWeighTableWidget = QtWidgets.QTableWidget(self.groupBox_10)
        self.EcoWeighTableWidget.setGeometry(QtCore.QRect(20, 33, 630, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EcoWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.EcoWeighTableWidget.setSizePolicy(sizePolicy)
        self.EcoWeighTableWidget.setDragEnabled(True)
        self.EcoWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.EcoWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.EcoWeighTableWidget.setRowCount(0)
        self.EcoWeighTableWidget.setObjectName("EcoWeighTableWidget")
        self.EcoWeighTableWidget.setColumnCount(0)
        self.EcoWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.EcoWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.EcoWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.EcoWeighTableWidget.verticalHeader().setStretchLastSection(True)
        self.EcoSaveCfgBtn = QtWidgets.QPushButton(self.groupBox_10)
        self.EcoSaveCfgBtn.setGeometry(QtCore.QRect(20, 302, 104, 24))
        self.EcoSaveCfgBtn.setObjectName("EcoSaveCfgBtn")
        self.EcoProgressBar = QtWidgets.QProgressBar(self.groupBox_10)
        self.EcoProgressBar.setGeometry(QtCore.QRect(170, 302, 371, 25))
        self.EcoProgressBar.setProperty("value", 0)
        self.EcoProgressBar.setObjectName("EcoProgressBar")
        self.EcoGetWeightBtn = QtWidgets.QPushButton(self.groupBox_10)
        self.EcoGetWeightBtn.setEnabled(True)
        self.EcoGetWeightBtn.setGeometry(QtCore.QRect(550, 300, 104, 24))
        self.EcoGetWeightBtn.setObjectName("EcoGetWeightBtn")
        self.toolBox.addItem(self.EconomicsQTBox, "")
        self.SocialQTBox = QtWidgets.QWidget()
        self.SocialQTBox.setGeometry(QtCore.QRect(0, 0, 676, 473))
        self.SocialQTBox.setObjectName("SocialQTBox")
        self.line_12 = QtWidgets.QFrame(self.SocialQTBox)
        self.line_12.setGeometry(QtCore.QRect(10, 400, 660, 15))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.SocTEdit = QtWidgets.QTextEdit(self.SocialQTBox)
        self.SocTEdit.setGeometry(QtCore.QRect(10, 420, 530, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.SocTEdit.sizePolicy().hasHeightForWidth())
        self.SocTEdit.setSizePolicy(sizePolicy)
        self.SocTEdit.setObjectName("SocTEdit")
        self.SocHelpBtn = QtWidgets.QPushButton(self.SocialQTBox)
        self.SocHelpBtn.setGeometry(QtCore.QRect(560, 420, 99, 24))
        self.SocHelpBtn.setObjectName("SocHelpBtn")
        self.EcoLbl_2 = QtWidgets.QLabel(self.SocialQTBox)
        self.EcoLbl_2.setGeometry(QtCore.QRect(6, 2, 51, 16))
        self.EcoLbl_2.setObjectName("EcoLbl_2")
        self.SocMapNameLbl = QtWidgets.QLabel(self.SocialQTBox)
        self.SocMapNameLbl.setGeometry(QtCore.QRect(88, 6, 431, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.SocMapNameLbl.setFont(font)
        self.SocMapNameLbl.setTextFormat(QtCore.Qt.AutoText)
        self.SocMapNameLbl.setObjectName("SocMapNameLbl")
        self.line_13 = QtWidgets.QFrame(self.SocialQTBox)
        self.line_13.setGeometry(QtCore.QRect(9, 27, 657, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.groupBox_9 = QtWidgets.QGroupBox(self.SocialQTBox)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 50, 651, 341))
        self.groupBox_9.setObjectName("groupBox_9")
        self.SocGetWeightBtn = QtWidgets.QPushButton(self.groupBox_9)
        self.SocGetWeightBtn.setEnabled(True)
        self.SocGetWeightBtn.setGeometry(QtCore.QRect(540, 290, 104, 24))
        self.SocGetWeightBtn.setObjectName("SocGetWeightBtn")
        self.SocWeighTableWidget = QtWidgets.QTableWidget(self.groupBox_9)
        self.SocWeighTableWidget.setGeometry(QtCore.QRect(10, 30, 630, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SocWeighTableWidget.sizePolicy().hasHeightForWidth())
        self.SocWeighTableWidget.setSizePolicy(sizePolicy)
        self.SocWeighTableWidget.setAcceptDrops(False)
        self.SocWeighTableWidget.setDragEnabled(True)
        self.SocWeighTableWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.SocWeighTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.SocWeighTableWidget.setRowCount(0)
        self.SocWeighTableWidget.setObjectName("SocWeighTableWidget")
        self.SocWeighTableWidget.setColumnCount(0)
        self.SocWeighTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.SocWeighTableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.SocWeighTableWidget.verticalHeader().setHighlightSections(True)
        self.SocWeighTableWidget.verticalHeader().setStretchLastSection(True)
        self.SocProgressBar = QtWidgets.QProgressBar(self.groupBox_9)
        self.SocProgressBar.setGeometry(QtCore.QRect(160, 290, 371, 25))
        self.SocProgressBar.setProperty("value", 0)
        self.SocProgressBar.setObjectName("SocProgressBar")
        self.SocSaveCfgBtn = QtWidgets.QPushButton(self.groupBox_9)
        self.SocSaveCfgBtn.setGeometry(QtCore.QRect(10, 290, 104, 24))
        self.SocSaveCfgBtn.setObjectName("SocSaveCfgBtn")
        self.toolBox.addItem(self.SocialQTBox, "")
        self.AnalysisQTBox = QtWidgets.QWidget()
        self.AnalysisQTBox.setGeometry(QtCore.QRect(0, 0, 676, 473))
        self.AnalysisQTBox.setObjectName("AnalysisQTBox")
        self.AnlsBtnBox = QtWidgets.QDialogButtonBox(self.AnalysisQTBox)
        self.AnlsBtnBox.setGeometry(QtCore.QRect(565, 504, 86, 23))
        self.AnlsBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.AnlsBtnBox.setObjectName("AnlsBtnBox")
        self.groupBox_5 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 10, 651, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.spinBoxClasNum = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBoxClasNum.setGeometry(QtCore.QRect(200, 30, 61, 22))
        self.spinBoxClasNum.setProperty("value", 5)
        self.spinBoxClasNum.setObjectName("spinBoxClasNum")
        self.RenderMapBtn = QtWidgets.QPushButton(self.groupBox_5)
        self.RenderMapBtn.setGeometry(QtCore.QRect(520, 30, 111, 24))
        self.RenderMapBtn.setObjectName("RenderMapBtn")
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 141, 20))
        self.label_7.setObjectName("label_7")
        self.groupBox_6 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 190, 651, 91))
        self.groupBox_6.setObjectName("groupBox_6")
        self.LabelCartogramCBox = QtWidgets.QComboBox(self.groupBox_6)
        self.LabelCartogramCBox.setGeometry(QtCore.QRect(171, 40, 291, 22))
        self.LabelCartogramCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.LabelCartogramCBox.setObjectName("LabelCartogramCBox")
        self.RenderCarogramBtn = QtWidgets.QPushButton(self.groupBox_6)
        self.RenderCarogramBtn.setGeometry(QtCore.QRect(520, 40, 111, 24))
        self.RenderCarogramBtn.setObjectName("RenderCarogramBtn")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 141, 20))
        self.label_5.setObjectName("label_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 100, 651, 81))
        self.groupBox_7.setObjectName("groupBox_7")
        self.GraphBtn = QtWidgets.QPushButton(self.groupBox_7)
        self.GraphBtn.setGeometry(QtCore.QRect(520, 30, 111, 24))
        self.GraphBtn.setObjectName("GraphBtn")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(20, 35, 111, 20))
        self.label_3.setObjectName("label_3")
        self.LabelListFieldsCBox = QtWidgets.QComboBox(self.groupBox_7)
        self.LabelListFieldsCBox.setGeometry(QtCore.QRect(170, 33, 291, 22))
        self.LabelListFieldsCBox.setMaximumSize(QtCore.QSize(16777215, 22))
        self.LabelListFieldsCBox.setObjectName("LabelListFieldsCBox")
        self.groupBox_8 = QtWidgets.QGroupBox(self.AnalysisQTBox)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 290, 651, 141))
        self.groupBox_8.setObjectName("groupBox_8")
        self.EnvSlider = QtWidgets.QSlider(self.groupBox_8)
        self.EnvSlider.setEnabled(True)
        self.EnvSlider.setGeometry(QtCore.QRect(230, 21, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvSlider.sizePolicy().hasHeightForWidth())
        self.EnvSlider.setSizePolicy(sizePolicy)
        self.EnvSlider.setProperty("value", 33)
        self.EnvSlider.setSliderPosition(33)
        self.EnvSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EnvSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.EnvSlider.setTickInterval(25)
        self.EnvSlider.setObjectName("EnvSlider")
        self.EcoSlider = QtWidgets.QSlider(self.groupBox_8)
        self.EcoSlider.setEnabled(True)
        self.EcoSlider.setGeometry(QtCore.QRect(230, 51, 291, 51))
        self.EcoSlider.setProperty("value", 33)
        self.EcoSlider.setOrientation(QtCore.Qt.Horizontal)
        self.EcoSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.EcoSlider.setTickInterval(25)
        self.EcoSlider.setObjectName("EcoSlider")
        self.SocSlider = QtWidgets.QSlider(self.groupBox_8)
        self.SocSlider.setEnabled(True)
        self.SocSlider.setGeometry(QtCore.QRect(230, 90, 291, 51))
        self.SocSlider.setProperty("value", 33)
        self.SocSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SocSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.SocSlider.setTickInterval(25)
        self.SocSlider.setObjectName("SocSlider")
        self.ecoWeightLbl_2 = QtWidgets.QLabel(self.groupBox_8)
        self.ecoWeightLbl_2.setGeometry(QtCore.QRect(20, 30, 161, 21))
        self.ecoWeightLbl_2.setObjectName("ecoWeightLbl_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_8)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 161, 21))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 131, 21))
        self.label_4.setObjectName("label_4")
        self.pushBtnEval = QtWidgets.QPushButton(self.groupBox_8)
        self.pushBtnEval.setEnabled(True)
        self.pushBtnEval.setGeometry(QtCore.QRect(550, 30, 81, 91))
        self.pushBtnEval.setObjectName("pushBtnEval")
        self.envWeightLbl = QtWidgets.QLabel(self.groupBox_8)
        self.envWeightLbl.setGeometry(QtCore.QRect(180, 30, 31, 21))
        self.envWeightLbl.setStyleSheet("background-color: rgb(175, 175, 175);\n"
"font: 75 8pt \"MS Shell Dlg 2\" rgb(255, 0, 0);\n"
"")
        self.envWeightLbl.setObjectName("envWeightLbl")
        self.ecoWeightLbl = QtWidgets.QLabel(self.groupBox_8)
        self.ecoWeightLbl.setGeometry(QtCore.QRect(180, 70, 31, 21))
        self.ecoWeightLbl.setStyleSheet("background-color: rgb(175, 175, 175);\n"
"font: 75 8pt \"MS Shell Dlg 2\" rgb(255, 0, 0);\n"
"")
        self.ecoWeightLbl.setObjectName("ecoWeightLbl")
        self.socWeightLbl = QtWidgets.QLabel(self.groupBox_8)
        self.socWeightLbl.setGeometry(QtCore.QRect(180, 110, 31, 21))
        self.socWeightLbl.setStyleSheet("background-color: rgb(175, 175, 175);\n"
"font: 75 8pt \"MS Shell Dlg 2\" rgb(255, 0, 0);\n"
"")
        self.socWeightLbl.setObjectName("socWeightLbl")
        self.toolBox.addItem(self.AnalysisQTBox, "")
        self.RulesQTBox = QtWidgets.QWidget()
        self.RulesQTBox.setGeometry(QtCore.QRect(0, 0, 676, 473))
        self.RulesQTBox.setObjectName("RulesQTBox")
        self.CritExtractBtn = QtWidgets.QPushButton(self.RulesQTBox)
        self.CritExtractBtn.setGeometry(QtCore.QRect(520, 10, 141, 31))
        self.CritExtractBtn.setObjectName("CritExtractBtn")
        self.RulesListWidget = QtWidgets.QListWidget(self.RulesQTBox)
        self.RulesListWidget.setGeometry(QtCore.QRect(10, 60, 651, 291))
        self.RulesListWidget.setObjectName("RulesListWidget")
        self.SaveRulesBtn = QtWidgets.QPushButton(self.RulesQTBox)
        self.SaveRulesBtn.setGeometry(QtCore.QRect(580, 360, 81, 31))
        self.SaveRulesBtn.setObjectName("SaveRulesBtn")
        self.groupBox_3 = QtWidgets.QGroupBox(self.RulesQTBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 400, 651, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.baseLbl = QtWidgets.QLabel(self.groupBox_3)
        self.baseLbl.setGeometry(QtCore.QRect(20, 20, 621, 21))
        self.baseLbl.setObjectName("baseLbl")
        self.toolBox.addItem(self.RulesQTBox, "")
        self.gridLayout.addWidget(self.toolBox, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(4)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.EnvTEdit, self.OutlEdt)
        Dialog.setTabOrder(self.OutlEdt, self.RetriveFileTBtn)
        Dialog.setTabOrder(self.RetriveFileTBtn, self.SetBtnBox)
        Dialog.setTabOrder(self.SetBtnBox, self.SetBtnHelp)
        Dialog.setTabOrder(self.SetBtnHelp, self.SetBtnAbout)
        Dialog.setTabOrder(self.SetBtnAbout, self.EnvHelpBtn)
        Dialog.setTabOrder(self.EnvHelpBtn, self.EcoTEdit)
        Dialog.setTabOrder(self.EcoTEdit, self.EcoHelpBtn)
        Dialog.setTabOrder(self.EcoHelpBtn, self.AnlsBtnBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SSAM - Spatial Sustainability Assessment Model"))
        self.SetBtnHelp.setText(_translate("Dialog", "Help"))
        self.SetBtnAbout.setText(_translate("Dialog", "About"))
        self.BaseLayerLbl.setText(_translate("Dialog", "TextLabel"))
        self.RetriveFileTBtn.setText(_translate("Dialog", "..."))
        self.groupBox.setTitle(_translate("Dialog", "Environmental criteria"))
        self.addLayerBtnENV.setText(_translate("Dialog", ">>>"))
        self.removeLayerBtnENV.setText(_translate("Dialog", "<<<"))
        self.groupBox_2.setTitle(_translate("Dialog", "Economic criteria"))
        self.removeLayerBtnECO.setText(_translate("Dialog", "<<<"))
        self.addLayerBtnECO.setText(_translate("Dialog", ">>>"))
        self.groupBox_4.setTitle(_translate("Dialog", "Social criteria"))
        self.addLayerBtnSOC.setText(_translate("Dialog", ">>>"))
        self.removeLayerBtnSOC.setText(_translate("Dialog", "<<<"))
        self.EcoFieldsLbl_2.setText(_translate("Dialog", "Base layer:"))
        self.EcoFieldsLbl_3.setText(_translate("Dialog", "Output layer"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Setting"))
        self.EnvLbl.setText(_translate("Dialog", "Layer     "))
        self.EnvHelpBtn.setText(_translate("Dialog", "Help"))
        self.groupBox_11.setTitle(_translate("Dialog", "GroupBox"))
        self.EnvGetWeightBtn.setText(_translate("Dialog", "Apply"))
        self.EnvSaveCfgBtn.setText(_translate("Dialog", "Save"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EnvironmentaleQTbox), _translate("Dialog", "Environmental criteria"))
        self.EcoLbl.setText(_translate("Dialog", "Layer     "))
        self.EcoHelpBtn.setText(_translate("Dialog", "Help"))
        self.groupBox_10.setTitle(_translate("Dialog", "GroupBox"))
        self.EcoSaveCfgBtn.setText(_translate("Dialog", "Save"))
        self.EcoGetWeightBtn.setText(_translate("Dialog", "Apply"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.EconomicsQTBox), _translate("Dialog", "Economic criteria"))
        self.SocHelpBtn.setText(_translate("Dialog", "Help"))
        self.EcoLbl_2.setText(_translate("Dialog", "Layer     "))
        self.groupBox_9.setTitle(_translate("Dialog", "Table"))
        self.SocGetWeightBtn.setText(_translate("Dialog", "Apply"))
        self.SocSaveCfgBtn.setText(_translate("Dialog", "Save"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.SocialQTBox), _translate("Dialog", "Social criteria "))
        self.groupBox_5.setTitle(_translate("Dialog", "Sustainability  maps"))
        self.RenderMapBtn.setText(_translate("Dialog", "Load maps"))
        self.label_7.setText(_translate("Dialog", "Classes in maps"))
        self.groupBox_6.setTitle(_translate("Dialog", "Sustainability cartograms"))
        self.RenderCarogramBtn.setText(_translate("Dialog", "Load cartogram"))
        self.label_5.setText(_translate("Dialog", "Select cartogram field"))
        self.groupBox_7.setTitle(_translate("Dialog", "Sustainability charts"))
        self.GraphBtn.setText(_translate("Dialog", "Build charts"))
        self.label_3.setText(_translate("Dialog", "Select name field"))
        self.groupBox_8.setTitle(_translate("Dialog", "Overall sustainability"))
        self.ecoWeightLbl_2.setText(_translate("Dialog", "Environmental dimension"))
        self.label_2.setText(_translate("Dialog", "Economic dimension"))
        self.label_4.setText(_translate("Dialog", "Social dimension"))
        self.pushBtnEval.setText(_translate("Dialog", "Evaluate"))
        self.envWeightLbl.setText(_translate("Dialog", "TextLabel"))
        self.ecoWeightLbl.setText(_translate("Dialog", "TextLabel"))
        self.socWeightLbl.setText(_translate("Dialog", "TextLabel"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.AnalysisQTBox), _translate("Dialog", "Analysis"))
        self.CritExtractBtn.setText(_translate("Dialog", " Extract rules"))
        self.SaveRulesBtn.setText(_translate("Dialog", "Save rules"))
        self.groupBox_3.setTitle(_translate("Dialog", "Active layer"))
        self.baseLbl.setText(_translate("Dialog", "TextLabel"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.RulesQTBox), _translate("Dialog", "Rules"))
